### PR TITLE
kustomize: add initial support for kustomize based templates

### PR DESCRIPTION
**Pull request by muvaf**
Adds initial support for kustomize engine. Kubectl comes with `kustomize`, so, we don't need an intermediate container to get the output for `kubectl apply`. Instead, we directly apply the kustomization via `kubectl apply -k <the configmap mount directory where our kustomization.yaml resides>`

@suskin I could not test this PR yet as I have neither the images you used nor the CR examples.

### CODE REVIEW

**Comment by muvaf** [comment]
@suskin I thought about this and I think we need a different approach here for kustomize. In Helm, there is just `values.yaml` that you put your overriding values in. However, in Kustomize `kustomization.yaml` usually just includes the [configuration for Kustomize](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/fields.md) like where the resources are, referencers etc as well as common things like `namePrefix`, `commonLabels`. So, you don't really give an actual value to override the downstream resources opposed to Helm's `values.yaml`. The main user flow is that you've got folders with resources and you create the same kind as an overlay, which includes your custom values for the env, and `kustomize` applies those patches during render.

How people have a central configuration piece to distribute high level config is that they have one object(usually a configmap) whose values are referenced in other resources like:
```
kind: Deployment
...
spec:
  someField: $(EXTERNAL_SERVICE)
```

`kustomization.yaml`:
```
kind: Kustomization
...
vars:
- name: EXTERNAL_SERVICE
   objref:
     kind: ConfigMap
     name: cfgmap
     apiVersion: v1
   fieldref:
     fieldpath: data.externalService
```
configmap:
```
kind: ConfigMap
...
data:
  externalService: 1.2.3.4
```

Or they have overlays for different configurations where they just patch the resources that need `EXTERNAL_SERVICE`. You can see the [this example](https://github.com/kubernetes-sigs/kustomize/tree/master/examples/wordpress) from kustomize repo.

We could possibly expose two fields like `values`(for central config map) and `kustomization` instead of only `kustomization`. Though, in this solution, the users would have to change their kustomize package to accomodate the values coming from that configmap.

The other choice is to expose kustomization and a `overlay` field that takes raw YAML input in CR spec where the users can add their patch objects. This is how kustomize overlays work but that's not a usual UX for custom resources.

**Comment by suskin** [comment]
> @suskin I could not test this PR yet as I have neither the images you used nor the CR examples.

@muvaf good point! I've now added an initial pass at integration testing to the destination branch; see the [README](https://github.com/suskin/stack-template-engine/tree/resource-engine-interface). It works for me with my local Docker Kubernetes; I believe with something like minikube, where it has a separate image registry, you'll need to add a step to copy the docker images into the cluster to get it to work properly. My changes don't currently have that step.

**Comment by suskin** [comment]
> @suskin I thought about this and I think we need a different approach here for kustomize

@muvaf I agree. The transformation of the input into something kustomize can konsume seems like the tricky part of integrating the kustomize engine in this way.

I would lean toward adding something that supports the var-oriented approach, since the overlay approach could theoretically be accomplished by someone without needing to use a mechanism we provide. For example, I could create a kustomization `myvariant` which adds my custom overlays and uses the shared kustomization as a base. So long as I don't need values known at runtime, it would work fine. It'd be a bit of a pain to package it all into an image, but that'll be less of a pain when we support loading stacks directly from git urls.

On the other hand, with the var-oriented approach, it seems like there's not a good way of negotiating the naming for the config map, based on my understanding. We'd either have to parse the kustomization and use the name specified there, and handle all edge cases with a nice UX, or we can generate that section of the configuration for people.

My preferred approach based on my understanding at this time would be something like:

* When we get a CR `A`, we look at the CRD `A_CRD`. For all of the fields declared in the schema for `A_CRD`, we create a var mapping based on the name of the field. Only one level of nesting is supported.
* We generate a config map `CM` containing the fields and values from `A`
* We generate the var configuration block for kustomize, using the name of `CM` and the mappings from `A_CRD`
* We create a kustomization `K` containing the var configuration block. `K` should use the stack's original kustomization as a base
* We run kustomize using `K`

What do you think?

**Comment by muvaf** [comment]
I thought about some more about my proposal above and examined kustomize examples. I think we need to cover the case where the kustomize git repo is not aware of the fact that a stack may deploy it, meaning a user should be able to use a kustomize folder as is. This is easy with helm since we have one place to override everything but in kustomize it's up to the author to select the inter-resource references and provide patches for any resource, including the ones that they use as eventual value provider.

In other words, the kustomize folder of the user already works on its own. So, the configmap(or other resource) referencing approach is probably in place if they need it in the first place. In order to make rendering use our values from the CR, we might need to have to find that config map and replace/append to it. Since we can't find it, user has to specify it. However, it's not certain that it's only one configmap or even a configmap. Honestly the more I think about my initial proposal, it feels like we try to do intrude to the user's kustomize setup too much. We can enforce that they should expect that such a configmap will come in, but then that will require them to modify their kustomize resources heavily.

I think I am leaning more towards that what we can do is to allow user to specify a full set of overlay that they'd normally do. What this means is that we allow user to create a `kustomization.yaml` and `overlay.yaml` on the CR. Let's say they have a Wordpress and the mysql endpoints are supplied through overlays like `prod` and `dev` and the default is hardcoded something like `localhost:1234`. What template stack would provide is that they can create a CRD that points to that git repo which contains their kustomize folder and a CR instance could include a spec field like `overlay` where they can provide a patch `Deployment` or `ConfigMap` object with values that they want, either prod IP or dev IP. If they use a configmap as central config store, they can patch that as well with the overlay. They should also be able to refer to object that already exists in the cluster such as a secret, because it won't make sense to put sensitive data into CR directly. I put an example in the end to show how it'd look like.

How it'd work is that the controller can merge all of the resources referred and the raw YAML given in `overlay` field into one YAML to be used as overlay by kustomize, i.e. `overlay.yaml`, and refer to that in our `kustomization.yaml`

The other use case is to apply different overlays that already exists in the repo, like in our [Argo CD](https://github.com/crossplaneio/crosscd/tree/master/classpacks/quickstart/dev) repo where you specify different bases for different environments. To accommodate this and other use cases that require direct `Kustomization` object access, we can provide a field for them to supply it.

In the final form, the spec looks like this:
```yaml
spec:
  kustomization:
    commonLabels:
      - environment: prod
    namePrefix: prod
  overlay: | # raw yaml
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: the-deployment
    spec:
      replicas: 3
  overlayRefs: # object reference type
  - apiVersion: v1
    kind: Secret
    name: prod-credentials
    namespace: default
```

The additions we'll make to their supplied `kustomization` are to `commonLabels` and `namePrefix`. What we'll do is prefix their `namePrefix` with `<cr name>-` and add additional labels to refer back to the CR.

How does that sound? @suskin

**Comment by suskin** [comment]
I like these ideas. Ok, let me organize things for my own thoughts a bit first.

Here are some of the questions we're asking ourselves at this point:

* Should we support the full expressiveness of kustomize?
  - If so, how?
* Should we try to match the interface of the helm CRs?
  - If so, how?

My goal at this time is to go from zero kustomize to some kustomize, so I'm looking for the simplest thing we can do to get something useful, so we can give ourselves more time to figure out the more challenging richer functionality for the long term. Some of these problems, such as supporting the full expressiveness of kustomize, seem like they could take some time and several iterations to solve properly.

I think it helps for me if we talk about the use-cases we want to support, to see if we can leave any of the problems for later. My understanding is that the desired use-cases are roughly the following:

* Use existing kustomizations.
* Use kustomizations that we make to provide functionality such as the minimal GCP stack.
  * Instantiate multiple non-conflicting variants of the same kustomization (such as with the minimal GCP stack).
  * Provide variant parameters as simple input variables instead of a full overlay

I believe we can satisfy these use-cases without supporting the full capabilities of kustomize. I'll explain with examples.

## Existing kustomizations

My understanding is that the most common kustomize pattern is to write a variant kustomization file that points at another kustomization as a base, and then to check the variant into version control.

Kustomize-specific stack contents:

```
# This shows filesystem contents of a stack image, but the files could also be in a git repo
# when git repo sources are supported
/.registry/resources/kustomization.yaml # This would be a variant which uses another kustomization as a base, either in the stack or in a git repo
/.registry/resources/overlays/myconfigmap.yaml # A sample representing a config map overlay for this variant
```

stack.yaml:

```yaml
behaviors:
- 
  engine:
    type: kustomize

  source:
    # Image is a stack image in this case, but could also point to a git repo when we support git repos
    image: myrepository/mykustomizestack:latest

  reconcile:
    # the "resources" path is used as the root of the kustomization
    - path: resources
# . . . other stack.yaml content is truncated
```

CR:

```yaml
kind: SampleKustomizePack
apiVersion: samples.stacks.crossplane.io/v1alpha1

metadata:
  name: sample-kustomize-pack

# Because the whole kustomization is in the stack, there is no
# spec portion of this CR
```

## Minimal GCP: Multiple non-conflicting variants

@muvaf I was originally reading the proposed design as supporting user-specified name prefixes, but then at the end it said we generate name prefixes and labels. Do we need to support user-specified name prefixes and labels? I'll assume yes, because reading it again, it sounds like the idea is that we'd support user-specified name prefixes and labels, but would modify them before using them.

### User-specified name prefixes and labels

Stack contents:

```
# This shows filesystem contents of a stack image, but the files could also be in a git repo
# when git repo sources are supported
/.registry/resources/kustomization.yaml # This would be a variant which uses another kustomization as a base, either in the stack or in a git repo
/.registry/resources/overlays/myconfigmap.yaml # A sample representing a config map overlay for this variant
```

stack.yaml:

```yaml
behaviors:
- 
  engine:
    type: kustomize

  source:
    # Image is a stack image in this case, but could also point to a git repo when we support git repos
    image: myrepository/mykustomizestack:latest

  reconcile:
    # the "resources" path is used as the root of the kustomization
    - path: resources

# . . . other stack.yaml content is truncated
```

CR:

```yaml
kind: SampleKustomizePack
apiVersion: samples.stacks.crossplane.io/v1alpha1

metadata:
  name: sample-kustomize-pack

spec:
  # This is exactly what was just proposed.
  #
  # Underneath, the engine would generate a kustomization which refers
  # to the stack's original kustomization, which it would find using the
  # specified `path` field on the hook configuration.
  #
  # Specifying resources and bases would not be supported (at this time).
  kustomization:
    commonLabels:
    - environment: prod
    namePrefix: prod
```     

## Minimal GCP: Variant inputs as simple parameters

Stack contents:

```
# This shows filesystem contents of a stack image, but the files could also be in a git repo
# when git repo sources are supported
/.registry/resources/kustomization.yaml # This would be a variant which uses another kustomization as a base, either in the stack or in a git repo
/.registry/resources/overlays/myconfigmap.yaml # A sample representing a config map overlay for this variant
```

stack.yaml:

```yaml
behaviors:
- 
  engine:
    type: kustomize
    vars:
      # Underneath, the kustomize part of the template stack controller would
      # generate a config map with this name, using the spec of the CR as
      # the data map for the config map. The idea is that the kustomization would have
      # a matching "vars:" block which refers to a configmap of this name, similar to
      # what the minimal GCP stack does (but with a config map).
      configmap: mycustominputcm

  source:
    # Image is a stack image in this case, but could also point to a git repo when we support git repos
    image: myrepository/mykustomizestack:latest

  reconcile:
    # the "resources" path is used as the root of the kustomization
    - path: resources

# . . . other stack.yaml content is truncated
```

CR:

```yaml
kind: SampleKustomizePack
apiVersion: samples.stacks.crossplane.io/v1alpha1

metadata:
  name: sample-kustomize-pack

spec:
  # Underneath, the engine would generate a config map which uses
  # the contents of this spec field as its data map, because of the configuration
  # for the stack in the stack's stack.yaml. This form assumes that a kustomization
  # that utilized this functionality used a single central config.
  # 
  # This is compatible with putting the "kustomization" field in this CR and
  # building a kustomization using the contents of the field, because the kustomization
  # could just ignore the contents of the "kustomization" field in the config map.
  region: us-east-1
  projectID: myprojectid
```   



@muvaf what do you think?

**Comment by muvaf** [comment]
I feel strongly that we should not impose the use of a `ConfigMap` in order to be able to deploy a kustomize pack. I'd not like users to make changes in their setup just to use template stacks because the only way to use it is having a central `ConfigMap`. I know you think that this is only the first iteration and we can change it but I feel like we're overestimating the effort we need to implement these, i.e. implementation of any of these designs isn't necessarily more work, in fact, IMO it's usually easier so long we can find something simple.

In Kustomize there are two inputs that users provide: `kustomization.yaml` and a set of patch objects that make up the overlay which could include a `ConfigMap` or just a `Deployment` that changes the image. My proposal included giving these in a raw format, however, I can see that you'd like to preserve the UX of giving individual parameters directly in `spec` like:
```yaml
spec:
  region: us-west2
  project: my-project
```
And I agree that this is a better UX than having to supply a full object with `apiVersion`, `kind` and friends.

What I think of something that can handle both is as following:
`stack.yaml`:
```yaml
behaviors:
  - engine:
      type: kustomize
      overlays:
      - from: "spec"
        to: # ObjectReference type
          apiVersion: v1
          kind: ConfigMap
          name: settings
          fieldPath: "data"
    source:
      # Image is a stack image in this case, but could also point to a git repo when we support git repos
      image: myrepository/mykustomizestack:latest
```
CR:
```yaml
kind: SampleKustomizePack
apiVersion: samples.stacks.crossplane.io/v1alpha1
metadata:
  name: sample-kustomize-pack
spec:
  region: us-east-1
  projectID: myprojectid
```

What will happen is that the controller will go over the `overlays` array and create an overlay object with type of `ConfigMap` and given name, then copy everything from `spec` of the CR to `data` of the ConfigMap. So, we let user define their overlay objects. If they'd like, they could do something like the following, too:
```yaml
behaviors:
  - engine:
      type: kustomize
      overlays:
      - from: "spec.instanceNum"
        to: # ObjectReference type
          apiVersion: apps/v1
          kind: Deployment
          name: nginx
          fieldPath: "spec.replicas"
    source:
      # Image is a stack image in this case, but could also point to a git repo when we support git repos
      image: myrepository/mykustomizestack:latest
```
CR:
```
kind: SampleKustomizePack
apiVersion: samples.stacks.crossplane.io/v1alpha1
metadata:
  name: sample-kustomize-pack
spec:
  instanceNum: 3
```

And what'll happen is that the controller will take value of `spec.instanceNum` from `SampleKustomizePack` and copy it to `spec.replicas` of the `Deployment` object. Where this solution falls short currently is the `Secret` objects, people can use different overlays (`dev`,`prod`) that changes only the credentials in a secret. However, it's not OK to supply sensitive data over CR. We can handle this via references but I think we can punt that use-case for now.

I will take some time off and before going I'd like to have something working. So, I'll start working on this but feel free to drop your comments.

**Comment by muvaf** [comment]
Forgot to add `kustomization.yaml` input part. I believe it could be given through the `stack.yaml` instead of the CR since it's a configuration for the rendering process rather than something that directly affects how your app works; this is decided via specific parameters on actual objects.
So, the `stack.yaml` could look like this:
```yaml
behaviors:
  - engine:
      type: kustomize
      kustomization: # Kustomization object type
        namePrefix: myprefix
        commonLabels: eu
        # and other Kustomization parameters
      overlays:
      - from: "spec.instanceNum"
        to: # ObjectReference type
          apiVersion: apps/v1
          kind: Deployment
          name: nginx
          fieldPath: "spec.replicas"
    source:
      # Image is a stack image in this case, but could also point to a git repo when we support git repos
      image: myrepository/mykustomizestack:latest
```

We'd still inject a namePrefix and a few commonLabels entries for system to work without conflicts.

**Comment by suskin** [comment]
> I'll start working on this

kk, sounds good to me. I agree with this approach

> I'd not like users to make changes in their setup . . . because the only way to use it is having a central ConfigMap

This makes sense. I didn't realize using other types was common.

> we let user define their overlay objects

Ok - so it sounds like everything in the `overlays` key would become a new object which is referenced as an overlay from the `kustomization.yaml` that kustomize runs against. Makes sense to me. I like that it's specified in the `stack.yaml`, and I like that it allows people to use other types other than ConfigMap for vars.

Other minor comments:

* For the `overlays:` key, it **seems** like we could also express the logic for our `helm2` transformation using the same format, so I was wondering whether we should try to use a more common name instead of `overlays` (such as `transformations`). But I think it's probably something which seems like it's a good idea but isn't, because they are used differently by the different engines.
* For injecting a namePrefix and a few commonLabels entries, I feel like as a user I'd prefer if I could be confident that what I specify is what I'll get, but I don't have any better ideas than what you're already planning on doing.

**Comment by muvaf** [comment]
> For the overlays: key, it seems like we could also express the logic for our helm2 transformation using the same format, so I was wondering whether we should try to use a more common name instead of overlays (such as transformations).

Possibly. They are not doing vastly different things, after all, it's user's definition of binding pairs of fields. However, in kustomize, user has to refer to an object whereas in helm it all goes to `values.yaml`. I feel like we can come back and consider this after getting the whole picture and seeing how we can find a common ground.

> For injecting a namePrefix and a few commonLabels entries, I feel like as a user I'd prefer if I could be confident that what I specify is what I'll get

We can skip touching `commonLabels` but we have to add a prefix to the resources we deploy in order to allow multiple CRs to deploy resources without conflict. How is multiple CR scenario handled in helm engine?

**Comment by muvaf** [comment]
@suskin This PR makes the job print out the final object YAMLs ready to be deployed with the image produced from that MinimalGCP PR here https://github.com/muvaf/minimal-gcp/pull/6

The reason that it doesn't deploy is because the generated job has `default` service account attached to it and that doesn't have the necessary permissions. I realized, right now, template stacks do not have anything related to RBACs, possibly because in helm2, it's not necessary since it's the `tiller` that does the actual deployment. We'd probably generate a service account per StackConfiguration and use that one for all of its jobs.

Anyway, I couldn't get around to work on the RBAC stuff. Right now, this works but testing is a bit hard; I added example CRs under `test` directory. I will polish this when I come back from vacation.

**Comment by muvaf** [comment]
I've added multiple field bindings per object, so, the structure's been changed a bit. That's how MinimalGCP `stack.yaml` looks like:
```yaml
---
apiVersion: helm.samples.stacks.crossplane.io/v1alpha1
kind: StackConfiguration
metadata:
  name: template-stack-test
spec:
  behaviors:
    crds:
      SampleClaim.samples.stacks.crossplane.io/v1alpha1:
        hooks:
          reconcile:
          - directory: 'resources'
        engine:
          type: kustomize
          overlays:
            - apiVersion: gcp.crossplane.io/v1alpha3
              kind: Provider
              name: gcp-provider
              bindings:
                - from: "spec.credentialsSecretRef"
                  to: "spec.credentialsSecretRef"
                - from: "spec.projectID"
                  to: "spec.projectID"
            - apiVersion: v1
              kind: ConfigMap
              name: gcp-config
              bindings:
                - from: "spec.region"
                  to: "data.region"
    source:
      image: crossplaneio/minimal-gcp:latest
```

**Comment by suskin** [comment]
> right now, template stacks do not have anything related to RBACs

That's true. In the `helm2` engine, tiller is not used; the reason is more because I wasn't using RBAC rules during testing, as I was running the controllers out-of-cluster using a privileged account. And I haven't gotten around to working on the real RBAC setup yet either, haha. Definitely possible that my local cluster is set up in a weird way that is too permissive.

> I've added multiple field bindings per object

Awesome!

> How is multiple CR scenario handled in helm engine?

It needs to be specified in the helm2 chart, which means either by using template variables in the CR names, or by using generated names instead of provided names. In other experiments in separate codebases, I've used the UID of the "claim" CR as a unique name suffix.

**Comment by suskin** [comment]
Closing this as it's a bit old now and has been superseded by other work

**Pull request closed without merging**
